<a href="https://colab.research.google.com/github/greensky0107/self_study/blob/main/Day70_MusicRecommendations.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Last.fm에서  dataset 받아서 전처리하기

데이터 용량이 너무 크니까 드라이브에 넣어놓고 진행  (session 초기화 때마다 시간 많이걸림)

In [32]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [34]:
import pandas as pd
import os


## 각자 경로에 맞게 고치기
#fname = os.getenv('HOME') + '/aiffel/recommendata_iu/data/lastfm-dataset-360K/usersha1-artmbid-artname-plays.tsv'

# Corrected file path to access from mounted Google Drive
fname = '/content/drive/MyDrive/rec_data/usersha1-artmbid-artname-plays.tsv'
col_names = ['user_id', 'artist_MBID', 'artist', 'play']   # 임의로 지정한 컬럼명
data = pd.read_csv(fname, sep='\t', names= col_names)      # sep='\t'로 주어야 tsv를 열 수 있습니다.
data.head(10)
data

,user_id,artist_MBID,artist,play
0,00000c289a1829a808ac09c00daf10bc3c4e223b,3bd73256-3905-4f3a-97e2-8b341527f805,betty blowtorch,2137
1,00000c289a1829a808ac09c00daf10bc3c4e223b,f2fb0ff0-5679-42ec-a55c-15109ce6e320,die Ärzte,1099
2,00000c289a1829a808ac09c00daf10bc3c4e223b,b3ae82c2-e60b-4551-a76d-6620f1b456aa,melissa etheridge,897
3,00000c289a1829a808ac09c00daf10bc3c4e223b,3d6bbeb7-f90e-4d10-b440-e153c0d10b53,elvenking,717
4,00000c289a1829a808ac09c00daf10bc3c4e223b,bbd2ffd7-17f4-4506-8572-c1ea58c3f9a8,juliette & the licks,706
...,...,...,...,...
17535650,"sep 20, 2008",7ffd711a-b34d-4739-8aab-25e045c246da,turbostaat,12
17535651,"sep 20, 2008",9201190d-409f-426b-9339-9bd7492443e2,cuba missouri,11
17535652,"sep 20, 2008",e7cf7ff9-ed2f-4315-aca8-bcbd3b2bfa71,little man tate,11
17535653,"sep 20, 2008",f6f2326f-6b25-4170-b89d-e235b25508e8,sigur rós,10
17535654,"sep 20, 2008",40f5d9e4-2de7-4f2d-ad41-e31a9a9fea27,the smiths,10

In [35]:
# 사용하는 컬럼만 남겨줍니다.
using_cols = ['user_id', 'artist', 'play']
data = data[using_cols]
data.head(10)

                                    user_id                   artist  play
0  00000c289a1829a808ac09c00daf10bc3c4e223b          betty blowtorch  2137
1  00000c289a1829a808ac09c00daf10bc3c4e223b                die Ärzte  1099
2  00000c289a1829a808ac09c00daf10bc3c4e223b        melissa etheridge   897
3  00000c289a1829a808ac09c00daf10bc3c4e223b                elvenking   717
4  00000c289a1829a808ac09c00daf10bc3c4e223b     juliette & the licks   706
5  00000c289a1829a808ac09c00daf10bc3c4e223b    red hot chili peppers   691
6  00000c289a1829a808ac09c00daf10bc3c4e223b                   magica   545
7  00000c289a1829a808ac09c00daf10bc3c4e223b  the black dahlia murder   507
8  00000c289a1829a808ac09c00daf10bc3c4e223b              the murmurs   424
9  00000c289a1829a808ac09c00daf10bc3c4e223b               lunachicks   403

In [36]:
data['artist'] = data['artist'].fillna('').str.lower() # 검색을 쉽게 하기 위해 아티스트 문자열을 소문자로 바꿔줍시다.
data.head(10)

/tmp/ipython-input-36-1509138353.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['artist'] = data['artist'].fillna('').str.lower() # 검색을 쉽게 하기 위해 아티스트 문자열을 소문자로 바꿔줍시다.

                                    user_id                   artist  play
0  00000c289a1829a808ac09c00daf10bc3c4e223b          betty blowtorch  2137
1  00000c289a1829a808ac09c00daf10bc3c4e223b                die ärzte  1099
2  00000c289a1829a808ac09c00daf10bc3c4e223b        melissa etheridge   897
3  00000c289a1829a808ac09c00daf10bc3c4e223b                elvenking   717
4  00000c289a1829a808ac09c00daf10bc3c4e223b     juliette & the licks   706
5  00000c289a1829a808ac09c00daf10bc3c4e223b    red hot chili peppers   691
6  00000c289a1829a808ac09c00daf10bc3c4e223b                   magica   545
7  00000c289a1829a808ac09c00daf10bc3c4e223b  the black dahlia murder   507
8  00000c289a1829a808ac09c00daf10bc3c4e223b              the murmurs   424
9  00000c289a1829a808ac09c00daf10bc3c4e223b               lunachicks   403

In [37]:
condition = (data['user_id']== data.loc[0, 'user_id'])
data.loc[condition]

                                     user_id                   artist  play
0   00000c289a1829a808ac09c00daf10bc3c4e223b          betty blowtorch  2137
1   00000c289a1829a808ac09c00daf10bc3c4e223b                die ärzte  1099
2   00000c289a1829a808ac09c00daf10bc3c4e223b        melissa etheridge   897
3   00000c289a1829a808ac09c00daf10bc3c4e223b                elvenking   717
4   00000c289a1829a808ac09c00daf10bc3c4e223b     juliette & the licks   706
5   00000c289a1829a808ac09c00daf10bc3c4e223b    red hot chili peppers   691
6   00000c289a1829a808ac09c00daf10bc3c4e223b                   magica   545
7   00000c289a1829a808ac09c00daf10bc3c4e223b  the black dahlia murder   507
8   00000c289a1829a808ac09c00daf10bc3c4e223b              the murmurs   424
9   00000c289a1829a808ac09c00daf10bc3c4e223b               lunachicks   403
10  00000c289a1829a808ac09c00daf10bc3c4e223b         walls of jericho   393
11  00000c289a1829a808ac09c00daf10bc3c4e223b           letzte instanz   387
12  00000c289a1829a808ac09c00daf10bc3c4e223b                goldfrapp   361
13  00000c289a1829a808ac09c00daf10bc3c4e223b               horrorpops   358
14  00000c289a1829a808ac09c00daf10bc3c4e223b             the butchies   329
15  00000c289a1829a808ac09c00daf10bc3c4e223b            jack off jill   316
16  00000c289a1829a808ac09c00daf10bc3c4e223b         babes in toyland   310
17  00000c289a1829a808ac09c00daf10bc3c4e223b         dropkick murphys   302
18  00000c289a1829a808ac09c00daf10bc3c4e223b            all:my:faults   288
19  00000c289a1829a808ac09c00daf10bc3c4e223b                 le tigre   281
20  00000c289a1829a808ac09c00daf10bc3c4e223b               schandmaul   244
21  00000c289a1829a808ac09c00daf10bc3c4e223b                    edguy   232
22  00000c289a1829a808ac09c00daf10bc3c4e223b      maximum the hormone   231
23  00000c289a1829a808ac09c00daf10bc3c4e223b                 all ends   229
24  00000c289a1829a808ac09c00daf10bc3c4e223b             jack johnson   227
25  00000c289a1829a808ac09c00daf10bc3c4e223b                eluveitie   222
26  00000c289a1829a808ac09c00daf10bc3c4e223b                rasputina   220
27  00000c289a1829a808ac09c00daf10bc3c4e223b    london after midnight   210
28  00000c289a1829a808ac09c00daf10bc3c4e223b              the killers   208
29  00000c289a1829a808ac09c00daf10bc3c4e223b                  mutyumu   205
30  00000c289a1829a808ac09c00daf10bc3c4e223b             judas priest   198
31  00000c289a1829a808ac09c00daf10bc3c4e223b               rob zombie   198
32  00000c289a1829a808ac09c00daf10bc3c4e223b             the bosshoss   189
33  00000c289a1829a808ac09c00daf10bc3c4e223b         blue öyster cult   185
34  00000c289a1829a808ac09c00daf10bc3c4e223b             sandra nasic   183
35  00000c289a1829a808ac09c00daf10bc3c4e223b               john mayer   182
36  00000c289a1829a808ac09c00daf10bc3c4e223b           sleater-kinney   175
37  00000c289a1829a808ac09c00daf10bc3c4e223b                  the who   168
38  00000c289a1829a808ac09c00daf10bc3c4e223b                 disciple   154
39  00000c289a1829a808ac09c00daf10bc3c4e223b                  tanzwut   153
40  00000c289a1829a808ac09c00daf10bc3c4e223b               guano apes   151
41  00000c289a1829a808ac09c00daf10bc3c4e223b       the rolling stones   150
42  00000c289a1829a808ac09c00daf10bc3c4e223b          little big town   145
43  00000c289a1829a808ac09c00daf10bc3c4e223b              team dresch   137
44  00000c289a1829a808ac09c00daf10bc3c4e223b                    betty   135
45  00000c289a1829a808ac09c00daf10bc3c4e223b                       l7   135
46  00000c289a1829a808ac09c00daf10bc3c4e223b                bif naked   134
47  00000c289a1829a808ac09c00daf10bc3c4e223b               girlschool   134
48  00000c289a1829a808ac09c00daf10bc3c4e223b          the wallflowers   131

In [38]:
# 유저 수
data['user_id'].nunique()

358868

In [39]:
# 아티스트 수
data['artist'].nunique()

291347

In [42]:
# 인기 많은 아티스트
artist_count = data.groupby('artist')['user_id'].count()
artist_count.sort_values(ascending=False).head(100)

artist
radiohead                77254
the beatles              76245
coldplay                 66658
red hot chili peppers    48924
muse                     46954
                         ...
beirut                   16750
cat power                16710
jimi hendrix             16690
black sabbath            16658
aphex twin               16539
Name: user_id, Length: 100, dtype: int64

In [41]:
# 유저별 몇 명의 아티스트를 듣고 있는지에 대한 통계
user_count = data.groupby('user_id')['artist'].count()
user_count.describe()

count    358868.000000
mean         48.863802
std           8.524191
min           1.000000
25%          46.000000
50%          49.000000
75%          51.000000
max         166.000000
Name: artist, dtype: float64

In [24]:
# 유저별 play횟수 중앙값에 대한 통계
user_median = data.groupby('user_id')['play'].median()
user_median.describe()

count    358868.000000
mean        142.187676
std         213.089902
min           1.000000
25%          32.000000
50%          83.000000
75%         180.000000
max       50142.000000
Name: play, dtype: float64

In [43]:
# 본인이 좋아하시는 아티스트 데이터로 바꿔서 추가하셔도 됩니다! 단, 이름은 꼭 데이터셋에 있는 것과 동일하게 맞춰주세요.
my_favorite = ['black eyed peas' , 'maroon5' ,'jason mraz' ,'coldplay' ,'beyoncé']

# 'zimin'이라는 user_id가 위 아티스트의 노래를 30회씩 들었다고 가정하겠습니다.
my_playlist = pd.DataFrame({'user_id': ['zimin']*5, 'artist': my_favorite, 'play':[30]*5})

if not data.isin({'user_id':['zimin']})['user_id'].any():  # user_id에 'zimin'이라는 데이터가 없다면
    data = pd.concat([data, my_playlist])                            # 위에 임의로 만든 my_playlist 데이터를 추가해 줍니다.

data.tail(10)       # 잘 추가되었는지 확인해 봅시다.

               user_id           artist  play
17535650  sep 20, 2008       turbostaat    12
17535651  sep 20, 2008    cuba missouri    11
17535652  sep 20, 2008  little man tate    11
17535653  sep 20, 2008        sigur rós    10
17535654  sep 20, 2008       the smiths    10
0                zimin  black eyed peas    30
1                zimin          maroon5    30
2                zimin       jason mraz    30
3                zimin         coldplay    30
4                zimin          beyoncé    30

In [44]:
# 고유한 유저, 아티스트를 찾아내는 코드
user_unique = data['user_id'].unique()
artist_unique = data['artist'].unique()

# 유저, 아티스트 indexing 하는 코드 idx는 index의 약자입니다.
user_to_idx = {v:k for k,v in enumerate(user_unique)}
artist_to_idx = {v:k for k,v in enumerate(artist_unique)}

In [46]:
# 인덱싱이 잘 되었는지 확인해 봅니다.
print(user_to_idx['zimin'])    # 358869명의 유저 중 마지막으로 추가된 유저이니 358868이 나와야 합니다.
print(artist_to_idx['black eyed peas'])

358868
376

In [47]:
# indexing을 통해 데이터 컬럼 내 값을 바꾸는 코드
# dictionary 자료형의 get 함수는 https://wikidocs.net/16 을 참고하세요.

# user_to_idx.get을 통해 user_id 컬럼의 모든 값을 인덱싱한 Series를 구해 봅시다.
# 혹시 정상적으로 인덱싱되지 않은 row가 있다면 인덱스가 NaN이 될 테니 dropna()로 제거합니다.
temp_user_data = data['user_id'].map(user_to_idx.get).dropna()
if len(temp_user_data) == len(data):   # 모든 row가 정상적으로 인덱싱되었다면
    print('user_id column indexing OK!!')
    data['user_id'] = temp_user_data   # data['user_id']을 인덱싱된 Series로 교체해 줍니다.
else:
    print('user_id column indexing Fail!!')

# artist_to_idx을 통해 artist 컬럼도 동일한 방식으로 인덱싱해 줍니다.
temp_artist_data = data['artist'].map(artist_to_idx.get).dropna()
if len(temp_artist_data) == len(data):
    print('artist column indexing OK!!')
    data['artist'] = temp_artist_data
else:
    print('artist column indexing Fail!!')

data

user_id column indexing OK!!
artist column indexing OK!!

    user_id  artist  play
0         0       0  2137
1         0       1  1099
2         0       2   897
3         0       3   717
4         0       4   706
..      ...     ...   ...
0    358868     376    30
1    358868  270115    30
2    358868    3746    30
3    358868      62    30
4    358868     396    30

[17535660 rows x 3 columns]

# Implicit Dataset (=Dense Matrix)을  CSR (Compressed Sparse Row)로 바꿔주기

In [48]:
# 1회만 play한 데이터의 비율을 보는 코드
only_one = data[data['play']==1]
one, all_data = len(only_one), len(data)
print(f'{one},{all_data}')
print(f'Ratio of only_one over all data is {one/all_data:.2%}')  # f-format에 대한 설명은 https://bit.ly/2DTLqYU

147739,17535660
Ratio of only_one over all data is 0.84%

In [49]:
# 실습 위에 설명보고 이해해서 만들어보기
from scipy.sparse import csr_matrix

num_user = data['user_id'].nunique()
num_artist = data['artist'].nunique()

csr_data = csr_matrix((data.play, (data.user_id, data.artist)), shape= (num_user, num_artist))
csr_data

<Compressed Sparse Row sparse matrix of dtype 'int64'
	with 17535578 stored elements and shape (358869, 291347)>

In [50]:
csr_data.shape

(358869, 291347)

## implicit 설치하고 추천 모델 만들기

In [51]:
!pip install implicit

Collecting implicit
  Downloading implicit-0.7.2-cp311-cp311-manylinux2014_x86_64.whl.metadata (6.1 kB)
Requirement already satisfied: numpy>=1.17.0 in /usr/local/lib/python3.11/dist-packages (from implicit) (2.0.2)
Requirement already satisfied: scipy>=0.16 in /usr/local/lib/python3.11/dist-packages (from implicit) (1.15.3)
Requirement already satisfied: tqdm>=4.27 in /usr/local/lib/python3.11/dist-packages (from implicit) (4.67.1)
Requirement already satisfied: threadpoolctl in /usr/local/lib/python3.11/dist-packages (from implicit) (3.6.0)
Downloading implicit-0.7.2-cp311-cp311-manylinux2014_x86_64.whl (8.9 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 8.9/8.9 MB 50.0 MB/s eta 0:00:00
Installing collected packages: implicit
Successfully installed implicit-0.7.2

In [52]:
from implicit.als import AlternatingLeastSquares
import os
import numpy as np

# implicit 라이브러리에서 권장하고 있는 부분입니다. 학습 내용과는 무관합니다.
os.environ['OPENBLAS_NUM_THREADS']='1'
os.environ['KMP_DUPLICATE_LIB_OK']='True'
os.environ['MKL_NUM_THREADS']='1'

In [54]:
# Implicit AlternatingLeastSquares 모델의 선언
als_model = AlternatingLeastSquares(factors=100, regularization=0.01, use_gpu=False, iterations=15, dtype=np.float32)

# 최신버전으로오면서

item X user 꼴의 matrix 를 받는게 아니라

반대로 바뀌었나봅니다

In [ ]:
# als 모델은 input으로 (item X user 꼴의 matrix를 받기 때문에 Transpose해줍니다.)
# csr_data_transpose = csr_data.T
# csr_data_transpose

# 추천 모델 훈련 및 살펴보기

In [55]:
# 모델 훈련  (3분 걸림)
als_model.fit(csr_data)

  0%|          | 0/15 [00:00<?, ?it/s]

# 유사한 Artist 찾아서 추천하기

In [56]:
print("user_factors shape:", als_model.user_factors.shape)
print("item_factors shape:", als_model.item_factors.shape)

user_factors shape: (358869, 100)
item_factors shape: (291347, 100)

In [57]:
zimin, black_eyed_peas = user_to_idx['zimin'], artist_to_idx['black eyed peas']
zimin_vector, black_eyed_peas_vector = als_model.user_factors[zimin], als_model.item_factors[black_eyed_peas]

print('슝=3')

슝=3

In [58]:
zimin_vector

array([-1.0459749 , -0.24879947,  0.714803  , -0.61057776,  0.7007368 ,
        0.21178664,  0.05629024, -1.1860046 , -0.06234834,  1.3272132 ,
       -1.0874574 , -0.12390914,  0.15553865, -0.3701618 , -0.03816914,
        0.48904282, -1.5943514 , -0.38625512,  0.23598392, -0.0248069 ,
        0.8320068 ,  0.11564911,  0.27717152, -0.34532395,  0.24159393,
        0.6170664 ,  0.3234901 , -0.25117344,  1.2006351 , -0.16665621,
        0.6071262 , -1.1268082 , -0.1048895 ,  0.08880545,  1.7245723 ,
       -0.32640186, -1.059444  ,  0.62891287, -0.48286906,  0.5656725 ,
       -0.47758657,  0.51791745,  0.3035751 , -0.569502  , -0.06577168,
        0.81652224,  0.6587707 , -0.45764968, -0.02332649,  0.84326184,
        0.16973129,  0.7147352 , -1.4058248 ,  0.42114684,  0.06394082,
        0.02512744,  0.820074  , -0.6165252 , -0.13208163,  0.11581093,
       -0.16123107,  0.7755566 , -0.916724  , -0.3265196 , -1.3418105 ,
        1.0188321 ,  1.4683281 , -0.06696782,  0.17900996, -0.29224458,
       -0.54159683, -1.4923784 , -0.7082194 ,  0.43375593,  0.19715461,
       -0.36141255, -0.4487413 ,  0.5103352 , -0.19677703, -0.34907243,
       -0.09442176, -0.0824731 ,  0.40630603,  1.0229809 ,  0.02855754,
        0.33536106, -1.7731694 ,  0.39722764,  0.3354645 ,  0.6551414 ,
        0.4761068 ,  0.49598098, -0.30673775, -0.32348025,  0.89984375,
       -0.5890521 ,  0.02240498,  0.5443698 ,  0.94075465,  0.4425422 ],
      dtype=float32)

In [59]:
black_eyed_peas_vector

array([ 0.00049129, -0.00033829,  0.00840721, -0.01454137,  0.00315764,
        0.01199998,  0.02597387, -0.00534875,  0.00500115,  0.03349324,
        0.01029348,  0.01114713,  0.01601194,  0.00294232,  0.00185457,
        0.01088767, -0.00832977, -0.00303013, -0.00441546,  0.00249183,
        0.02188756,  0.00746228,  0.00261754, -0.01058242,  0.0023272 ,
        0.01722872,  0.00567818,  0.00291025,  0.02397893,  0.01051947,
        0.01396838, -0.00343027,  0.00219819,  0.02075583,  0.02932942,
        0.01214747, -0.00519846,  0.01386011,  0.00679171,  0.01241601,
        0.00665276,  0.0096497 ,  0.00756229, -0.00332212,  0.00519433,
        0.0059864 ,  0.0141292 ,  0.00619981,  0.00659922,  0.02714339,
        0.0158544 ,  0.02093596, -0.00898764,  0.00897776, -0.00218433,
        0.01229014,  0.0186027 ,  0.001884  ,  0.00954914,  0.00941185,
       -0.00515254,  0.002972  , -0.01090183,  0.00631958, -0.02259984,
        0.01288994,  0.01844883,  0.00823092,  0.00682902, -0.00973164,
       -0.00574729,  0.00088779, -0.0025726 , -0.00164828, -0.0014932 ,
       -0.00679363,  0.01190653,  0.01299032,  0.00340565,  0.00841662,
        0.01169773,  0.00268174,  0.00655052,  0.00298016,  0.00651359,
        0.01202155, -0.03165146, -0.00208541,  0.02333245,  0.02026864,
        0.00685242,  0.01938488, -0.00414322,  0.00141822,  0.02370041,
        0.00528981, -0.00522094,  0.0048858 ,  0.02235455,  0.00798483],
      dtype=float32)

In [60]:
# zimin과 black_eyed_peas를 내적하는 코드
np.dot(zimin_vector, black_eyed_peas_vector)

np.float32(0.5397125)

In [61]:
queen = artist_to_idx['queen']
queen_vector = als_model.item_factors[queen]
np.dot(zimin_vector, queen_vector)

np.float32(0.31817734)

In [62]:
# coldplay와 유사한 artist 찾기
favorite_artist = 'coldplay'
artist_id = artist_to_idx[favorite_artist]
similar_artist = als_model.similar_items(artist_id, N=15)
similar_artist

(array([  62,  277,   28,    5,  217,  473,  247,  694,  418,  910,  490,
          55, 1018,  268,  782], dtype=int32),
 array([1.        , 0.9873715 , 0.98151517, 0.9773359 , 0.97444695,
        0.9677907 , 0.95892745, 0.9555562 , 0.95293605, 0.95152366,
        0.9512598 , 0.94833463, 0.9438292 , 0.9382341 , 0.9380084 ],
       dtype=float32))

In [63]:
#artist_to_idx 를 뒤집어, index로부터 artist 이름을 얻는 dict를 생성합니다.
idx_to_artist = {v:k for k,v in artist_to_idx.items()}
[idx_to_artist[i[0]] for i in similar_artist]

['coldplay', 'die ärzte']

In [64]:
def get_similar_artist(artist_name: str):
    artist_id = artist_to_idx[artist_name]
    similar_artist = als_model.similar_items(artist_id)
    similar_artist = [idx_to_artist[i] for i in similar_artist[0]]
    return similar_artist

print("슝=3")

슝=3

In [65]:
get_similar_artist('2pac')

['2pac',
 'snoop dogg',
 'the game',
 'nas',
 'notorious b.i.g.',
 '50 cent',
 'dr. dre',
 'jay-z',
 'ice cube',
 'dmx']

In [66]:
get_similar_artist('lady gaga')

['lady gaga',
 'rihanna',
 'britney spears',
 'beyoncé',
 'katy perry',
 'the pussycat dolls',
 'christina aguilera',
 'justin timberlake',
 'nelly furtado',
 'mariah carey']

# implicit library에서 오류 발생
filter_already_liked_items=True 로 두면 뭔가 오류가난다

노드에서도 이 부분이 제대로 작동을 안한다고 하는데
최신버전에서도 다른 오류가있는것으로 보임

In [67]:
user = user_to_idx['zimin']
# recommend에서는 user*item CSR Matrix를 받습니다.

# artist_recommended = als_model.recommend(user, csr_data, N=20, filter_already_liked_items=True)
artist_recommended = als_model.recommend(user, csr_data, N=20, filter_already_liked_items=False)
artist_recommended

(array([ 376,  369,  350,  550, 3746, 1800,  396,  354,  274,  409,  355,
         391, 2249,  724,  627,  382,  564, 5555,  621, 2902], dtype=int32),
 array([0.5397124 , 0.4757602 , 0.4637046 , 0.46328142, 0.46286798,
        0.45795545, 0.456182  , 0.453803  , 0.44161022, 0.43446752,
        0.42620808, 0.41947147, 0.41944957, 0.3979221 , 0.39665145,
        0.39490744, 0.3936944 , 0.39286882, 0.39167696, 0.38021842],
       dtype=float32))

In [68]:
[idx_to_artist[i] for i in artist_recommended[0]]

['black eyed peas',
 'justin timberlake',
 'rihanna',
 'britney spears',
 'jason mraz',
 'lady gaga',
 'beyoncé',
 'nelly furtado',
 'michael jackson',
 'amy winehouse',
 'madonna',
 'christina aguilera',
 'katy perry',
 'lily allen',
 'maroon 5',
 'mika',
 'kanye west',
 'timbaland',
 'alicia keys',
 'james blunt']

In [69]:
rihanna = artist_to_idx['rihanna']
explain = als_model.explain(user, csr_data, itemid=rihanna)

In [70]:
[(idx_to_artist[i[0]], i[1]) for i in explain[1]]

[('beyoncé', np.float64(0.227279938754547)),
 ('black eyed peas', np.float64(0.14802765562694703)),
 ('jason mraz', np.float64(0.04935338943490084)),
 ('coldplay', np.float64(0.041237807802164655)),
 ('maroon5', np.float64(-0.00039770873800902215))]